apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: bytecart-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bytecart-db
  template:
    metadata:
      labels:
        app: bytecart-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "bytecartdb123"
            - name: POSTGRES_DB
              value: "bytecart"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: bytecart-db-pvc
